In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\danay\OneDrive\Desktop\AUS\Spring20\MachineLearning\FinancialDataProject\200-financial-indicators-of-us-stocks-20142018\2014_Financial_Data.csv', index_col = "Abbrv")

In [3]:
df.shape

(3808, 224)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3808 entries, PG to WTT
Columns: 224 entries, Revenue to Class
dtypes: float64(222), int64(1), object(1)
memory usage: 6.5+ MB

In [5]:
df.head()

,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,Interest Expense,Earnings before Tax,...,Receivables growth,Inventory Growth,Asset Growth,Book Value per Share Growth,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,Sector,2015 PRICE VAR [%],Class
Abbrv,,,,,,,,,,,,,,,,,,,,,
PG,7.440100e+10,-0.0713,3.903000e+10,3.537100e+10,0.0,2.146100e+10,2.146100e+10,1.391000e+10,7.090000e+08,1.449400e+10,...,-0.0187,-0.0217,0.0359,0.0316,0.1228,0.0000,-0.1746,Consumer Defensive,-9.323276,0
VIPS,3.734148e+09,1.1737,2.805625e+09,9.285226e+08,108330319.7,3.441414e+08,7.939267e+08,1.345959e+08,1.214869e+07,1.753823e+08,...,NaN,NaN,NaN,NaN,NaN,1.6484,1.7313,Consumer Defensive,-25.512193,0
KR,9.837500e+10,0.0182,7.813800e+10,2.023700e+10,0.0,1.519600e+10,1.751200e+10,2.725000e+09,4.430000e+08,2.270000e+09,...,0.0618,0.0981,0.1886,0.3268,0.2738,0.0000,0.0234,Consumer Defensive,33.118297,1
RAD,2.552641e+10,0.0053,1.820268e+10,7.323734e+09,0.0,6.561162e+09,6.586482e+09,7.372520e+08,4.245910e+08,2.502180e+08,...,0.0211,-0.0510,-0.0189,0.1963,-0.0458,0.0000,-0.0060,Consumer Defensive,2.752291,1
GIS,1.790960e+10,0.0076,1.153980e+10,6.369800e+09,0.0,3.474300e+09,3.412400e+09,2.957400e+09,3.024000e+08,2.707700e+09,...,0.0257,0.0090,0.0215,0.0274,0.1025,0.0000,-0.0220,Consumer Defensive,12.897715,1

In [6]:
df.tail()

,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,Interest Expense,Earnings before Tax,...,Receivables growth,Inventory Growth,Asset Growth,Book Value per Share Growth,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,Sector,2015 PRICE VAR [%],Class
Abbrv,,,,,,,,,,,,,,,,,,,,,
TSRI,49529867.0,0.1028,41251638.0,8278229.0,0.0,8253061.0,8253061.0,25168.0,0.0,-68936.0,...,-0.0384,0.0000,-0.0041,-0.0049,0.0000,0.0000,0.0213,Technology,29.362884,1
TZOO,153240000.0,-0.1019,19174000.0,134066000.0,11326000.0,112513000.0,116256000.0,17810000.0,0.0,17901000.0,...,0.1529,0.0000,-0.1872,0.1823,0.0000,0.2830,-0.0637,Technology,-31.167763,0
USATP,42000000.0,NaN,27000000.0,15000000.0,NaN,14000000.0,15000000.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Technology,-23.558900,0
WSTG,340758000.0,0.1344,315948000.0,24810000.0,0.0,16513000.0,16513000.0,8297000.0,-472000.0,8758000.0,...,-0.0333,0.1338,0.0023,0.0890,0.0000,0.0000,0.0650,Technology,7.779579,1
WTT,40337368.0,0.1925,21293675.0,19043693.0,3379920.0,10984771.0,14364691.0,4679002.0,0.0,4588870.0,...,-0.0469,0.0455,-0.1646,-0.0226,-0.4594,0.2778,-0.0268,Technology,-34.099613,0

In [7]:
list(df.columns)

['Revenue',
 'Revenue Growth',
 'Cost of Revenue',
 'Gross Profit',
 'R&D Expenses',
 'SG&A Expense',
 'Operating Expenses',
 'Operating Income',
 'Interest Expense',
 'Earnings before Tax',
 'Income Tax Expense',
 'Net Income - Non-Controlling int',
 'Net Income - Discontinued ops',
 'Net Income',
 'Preferred Dividends',
 'Net Income Com',
 'EPS',
 'EPS Diluted',
 'Weighted Average Shs Out',
 'Weighted Average Shs Out (Dil)',
 'Dividend per Share',
 'Gross Margin',
 'EBITDA Margin',
 'EBIT Margin',
 'Profit Margin',
 'Free Cash Flow margin',
 'EBITDA',
 'EBIT',
 'Consolidated Income',
 'Earnings Before Tax Margin',
 'Net Profit Margin',
 'Cash and cash equivalents',
 'Short-term investments',
 'Cash and short-term investments',
 'Receivables',
 'Inventories',
 'Total current assets',
 'Property, Plant & Equipment Net',
 'Goodwill and Intangible Assets',
 'Long-term investments',
 'Tax assets',
 'Total non-current assets',
 'Total assets',
 'Payables',
 'Short-term debt',
 'Total current liabilities',
 'Long-term debt',
 'Total debt',
 'Deferred revenue',
 'Tax Liabilities',
 'Deposit Liabilities',
 'Total non-current liabilities',
 'Total liabilities',
 'Other comprehensive income',
 'Retained earnings (deficit)',
 'Total shareholders equity',
 'Investments',
 'Net Debt',
 'Other Assets',
 'Other Liabilities',
 'Depreciation & Amortization',
 'Stock-based compensation',
 'Operating Cash Flow',
 'Capital Expenditure',
 'Acquisitions and disposals',
 'Investment purchases and sales',
 'Investing Cash flow',
 'Issuance (repayment) of debt',
 'Issuance (buybacks) of shares',
 'Dividend payments',
 'Financing Cash Flow',
 'Effect of forex changes on cash',
 'Net cash flow / Change in cash',
 'Free Cash Flow',
 'Net Cash/Marketcap',
 'priceBookValueRatio',
 'priceToBookRatio',
 'priceToSalesRatio',
 'priceEarningsRatio',
 'priceToFreeCashFlowsRatio',
 'priceToOperatingCashFlowsRatio',
 'priceCashFlowRatio',
 'priceEarningsToGrowthRatio',
 'priceSalesRatio',
 'dividendYield',
 'enterpriseValueMultiple',
 'priceFairValue',
 'ebitperRevenue',
 'ebtperEBIT',
 'niperEBT',
 'grossProfitMargin',
 'operatingProfitMargin',
 'pretaxProfitMargin',
 'netProfitMargin',
 'effectiveTaxRate',
 'returnOnAssets',
 'returnOnEquity',
 'returnOnCapitalEmployed',
 'nIperEBT',
 'eBTperEBIT',
 'eBITperRevenue',
 'payablesTurnover',
 'inventoryTurnover',
 'fixedAssetTurnover',
 'assetTurnover',
 'currentRatio',
 'quickRatio',
 'cashRatio',
 'daysOfSalesOutstanding',
 'daysOfInventoryOutstanding',
 'operatingCycle',
 'daysOfPayablesOutstanding',
 'cashConversionCycle',
 'debtRatio',
 'debtEquityRatio',
 'longtermDebtToCapitalization',
 'totalDebtToCapitalization',
 'interestCoverage',
 'cashFlowToDebtRatio',
 'companyEquityMultiplier',
 'operatingCashFlowPerShare',
 'freeCashFlowPerShare',
 'cashPerShare',
 'payoutRatio',
 'operatingCashFlowSalesRatio',
 'freeCashFlowOperatingCashFlowRatio',
 'cashFlowCoverageRatios',
 'shortTermCoverageRatios',
 'capitalExpenditureCoverageRatios',
 'dividendpaidAndCapexCoverageRatios',
 'dividendPayoutRatio',
 'Revenue per Share',
 'Net Income per Share',
 'Operating Cash Flow per Share',
 'Free Cash Flow per Share',
 'Cash per Share',
 'Book Value per Share',
 'Tangible Book Value per Share',
 'Shareholders Equity per Share',
 'Interest Debt per Share',
 'Market Cap',
 'Enterprise Value',
 'PE ratio',
 'Price to Sales Ratio',
 'POCF ratio',
 'PFCF ratio',
 'PB ratio',
 'PTB ratio',
 'EV to Sales',
 'Enterprise Value over EBITDA',
 'EV to Operating cash flow',
 'EV to Free cash flow',
 'Earnings Yield',
 'Free Cash Flow Yield',
 'Debt to Equity',
 'Debt to Assets',
 'Net Debt to EBITDA',
 'Current ratio',
 'Interest Coverage',
 'Income Quality',
 'Dividend Yield',
 'Payout Ratio',
 'SG&A to Revenue',
 'R&D to Revenue',
 'Intangibles to Total Assets',
 'Capex to Operating Cash Flow',
 'Capex to Revenue',
 'Capex to Depreciation',
 'Stock-based compensation to Revenue',
 'Graham Number',
 'ROIC',
 'Return on Tangible Assets',
 'Graham Net-Net',
 'Working Capital',
 'Tangible Asset Value',
 'Net Current Asset Value',
 'Invested Capital',
 'Average Receivables',
 'Average Payables',
 'Average Inventory',
 'Days Sales Outstanding',
 'Days Payables Outstanding',
 'Days of Inventory on Hand',
 'Receivables Turnover',
 'Payables Turnover',
 'Inventory Turnover',
 'ROE',
 'Capex per Share',
 'Gross Profit Growth',
 'EBIT Growth',
 'Operating Income Growth',
 'Net Income Growth',
 'EPS Growth',
 'EPS Diluted Growth',
 'Weighted Average Shares Growth',
 'Weighted Average Shares Diluted Growth',
 'Dividends per Share Growth',
 'Operating Cash Flow growth',
 'Free Cash Flow growth',
 '10Y Revenue Growth (per Share)',
 '5Y Revenue Growth (per Share)',
 '3Y Revenue Growth (per Share)',
 '10Y Operating CF Growth (per Share)',
 '5Y Operating CF Growth (per Share)',
 '3Y Operating CF Growth (per Share)',
 '10Y Net Income Growth (per Share)',
 '5Y Net Income Growth (per Share)',
 '3Y Net Income Growth (per Share)',
 '10Y Shareholders Equity Growth (per Share)',
 '5Y Shareholders Equity Growth (per Share)',
 '3Y Shareholders Equity Growth (per Share)',
 '10Y Dividend per Share Growth (per Share)',
 '5Y Dividend per Share Growth (per Share)',
 '3Y Dividend per Share Growth (per Share)',
 'Receivables growth',
 'Inventory Growth',
 'Asset Growth',
 'Book Value per Share Growth',
 'Debt Growth',
 'R&D Expense Growth',
 'SG&A Expenses Growth',
 'Sector',
 '2015 PRICE VAR [%]',
 'Class']

In [8]:
df['2015 PRICE VAR [%]'].describe()

count    3.808000e+03
mean     9.751560e+02
std      4.098461e+04
min     -1.003972e+02
25%     -2.857143e+01
50%     -5.281842e+00
75%      1.331484e+01
max      2.418601e+06
Name: 2015 PRICE VAR [%], dtype: float64

In [9]:
pricevar = df[['2015 PRICE VAR [%]']]

In [10]:
pricevar

       2015 PRICE VAR [%]
Abbrv
PG              -9.323276
VIPS           -25.512193
KR              33.118297
RAD              2.752291
GIS             12.897715
...                   ...
TSRI            29.362884
TZOO           -31.167763
USATP          -23.558900
WSTG             7.779579
WTT            -34.099613

[3808 rows x 1 columns]

In [11]:
pricevar.sort_values(by='2015 PRICE VAR [%]', ascending = False)

       2015 PRICE VAR [%]
Abbrv
GNL          2.418601e+06
BW           6.955667e+05
NK           1.732000e+05
PUB          1.443588e+05
RUN          7.836667e+04
...                   ...
RGSE        -9.427273e+01
AAMC        -9.475518e+01
FTAI        -9.828955e+01
ARA         -9.833333e+01
RHE         -1.003972e+02

[3808 rows x 1 columns]

In [12]:
def classifying(x):
    if x > 1: 
        if x < 10:
            return "Class F"
        if x < 100:
            return "Class E"
        if x < 1000:
            return "Class D"
        if x < 10000:
            return "Class C"
        if x < 100000:
            return "Class B"
        if x > 1000000:
            return "Class A"
    
    else:
        if x > -10:
            return "Class W"
        if x > -100:
            return "Class X"
        if x > -1000:
            return "Class Y"
        if x < 1000:
            return "Class Z"

In [13]:
df["classes"] = df['2015 PRICE VAR [%]'].apply(classifying)
df

,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,Interest Expense,Earnings before Tax,...,Inventory Growth,Asset Growth,Book Value per Share Growth,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,Sector,2015 PRICE VAR [%],Class,classes
Abbrv,,,,,,,,,,,,,,,,,,,,,
PG,7.440100e+10,-0.0713,3.903000e+10,3.537100e+10,0.0,2.146100e+10,2.146100e+10,1.391000e+10,7.090000e+08,1.449400e+10,...,-0.0217,0.0359,0.0316,0.1228,0.0000,-0.1746,Consumer Defensive,-9.323276,0,Class X
VIPS,3.734148e+09,1.1737,2.805625e+09,9.285226e+08,108330319.7,3.441414e+08,7.939267e+08,1.345959e+08,1.214869e+07,1.753823e+08,...,NaN,NaN,NaN,NaN,1.6484,1.7313,Consumer Defensive,-25.512193,0,Class Y
KR,9.837500e+10,0.0182,7.813800e+10,2.023700e+10,0.0,1.519600e+10,1.751200e+10,2.725000e+09,4.430000e+08,2.270000e+09,...,0.0981,0.1886,0.3268,0.2738,0.0000,0.0234,Consumer Defensive,33.118297,1,Class E
RAD,2.552641e+10,0.0053,1.820268e+10,7.323734e+09,0.0,6.561162e+09,6.586482e+09,7.372520e+08,4.245910e+08,2.502180e+08,...,-0.0510,-0.0189,0.1963,-0.0458,0.0000,-0.0060,Consumer Defensive,2.752291,1,Class F
GIS,1.790960e+10,0.0076,1.153980e+10,6.369800e+09,0.0,3.474300e+09,3.412400e+09,2.957400e+09,3.024000e+08,2.707700e+09,...,0.0090,0.0215,0.0274,0.1025,0.0000,-0.0220,Consumer Defensive,12.897715,1,Class E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TSRI,4.952987e+07,0.1028,4.125164e+07,8.278229e+06,0.0,8.253061e+06,8.253061e+06,2.516800e+04,0.000000e+00,-6.893600e+04,...,0.0000,-0.0041,-0.0049,0.0000,0.0000,0.0213,Technology,29.362884,1,Class E
TZOO,1.532400e+08,-0.1019,1.917400e+07,1.340660e+08,11326000.0,1.125130e+08,1.162560e+08,1.781000e+07,0.000000e+00,1.790100e+07,...,0.0000,-0.1872,0.1823,0.0000,0.2830,-0.0637,Technology,-31.167763,0,Class Y
USATP,4.200000e+07,NaN,2.700000e+07,1.500000e+07,NaN,1.400000e+07,1.500000e+07,0.000000e+00,0.000000e+00,0.000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,Technology,-23.558900,0,Class Y
WSTG,3.407580e+08,0.1344,3.159480e+08,2.481000e+07,0.0,1.651300e+07,1.651300e+07,8.297000e+06,-4.720000e+05,8.758000e+06,...,0.1338,0.0023,0.0890,0.0000,0.0000,0.0650,Technology,7.779579,1,Class F
WTT,4.033737e+07,0.1925,2.129368e+07,1.904369e+07,3379920.0,1.098477e+07,1.436469e+07,4.679002e+06,0.000000e+00,4.588870e+06,...,0.0455,-0.1646,-0.0226,-0.4594,0.2778,-0.0268,Technology,-34.099613,0,Class Y

In [14]:
pricevar["classes"] = df['2015 PRICE VAR [%]'].apply(classifying)
pricevar

C:\Users\danay\Anaconda3\envs\deeplearning\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

       2015 PRICE VAR [%]  classes
Abbrv
PG              -9.323276  Class X
VIPS           -25.512193  Class Y
KR              33.118297  Class E
RAD              2.752291  Class F
GIS             12.897715  Class E
...                   ...      ...
TSRI            29.362884  Class E
TZOO           -31.167763  Class Y
USATP          -23.558900  Class Y
WSTG             7.779579  Class F
WTT            -34.099613  Class Y

[3808 rows x 2 columns]